app = "go-out-planner-server"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile.server"

[deploy]
  release_command = "npx prisma migrate deploy --schema=packages/server/prisma/schema.prisma"

[http_service]
  internal_port = 3001
  force_https = true

[[vm]]
  memory = "512mb"
  cpus = 1
