app = "go-out-planner-client"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile.client"
  [build.args]
    VITE_API_URL = "https://go-out-planner-client.fly.dev"

[http_service]
  internal_port = 80
  force_https = true

[[vm]]
  memory = "256mb"
  cpus = 1
